default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: wealthos_development

test:
  <<: *default
  database: wealthos_test

production:
  <<: *default
  database: wealthos_production
  url: <%= ENV['DATABASE_URL'] %>